{
 "title": "pipeline-monitor-dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "ML Prediction API Traffic",
   "type": "timeseries",
   "description": "ML Prediction API Traffic",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{job=\"pipeline-monitor\"}[1m]))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Service Health Status",
   "type": "timeseries",
   "description": "Service Health Status",
   "gridPos": { "h": 12, "w": 18, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "redis_memory_used_bytes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 13, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "redis_memory_used_bytes\n", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Demo App – Total Requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(demo_app_requests_total) by (instance)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pipeline Monitor – Request Rate",
   "type": "timeseries",
   "description": "Pipeline Monitor – Request Rate",
   "gridPos": { "h": 20, "w": 23, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    { "expr": "rate(http_requests_total[1m])", "legendFormat": "__auto" },
    {
     "expr": "sum(rate(http_requests_total[1m])) by (job)\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}